"""add priority to batch_selectors

Revision ID: 1f66bdffd67a
Revises: f8f703953fe0
Create Date: 2026-07-19 09:47:06.891513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f66bdffd67a'
down_revision: Union[str, None] = 'f8f703953fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_selectors', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch_selectors', 'priority')
    # ### end Alembic commands ###
