"""initial schema

Revision ID: f8f703953fe0
Revises: 
Create Date: 2026-07-19 09:20:45.504526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8f703953fe0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('migration_item_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('previous_state', sa.String(length=30), nullable=True),
    sa.Column('new_state', sa.String(length=30), nullable=True),
    sa.Column('operation', sa.String(length=60), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('final_name', sa.Text(), nullable=True),
    sa.Column('name_decision_source', sa.String(length=30), nullable=True),
    sa.Column('changed_by_user', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_events_batch_id'), 'journal_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_journal_events_correlation_id'), 'journal_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_journal_events_migration_item_id'), 'journal_events', ['migration_item_id'], unique=False)
    op.create_index(op.f('ix_journal_events_timestamp'), 'journal_events', ['timestamp'], unique=False)
    op.create_table('repository_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repository_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_description', sa.Text(), nullable=False),
    sa.Column('root_folder_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('folder_count', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.JSON(), nullable=False),
    sa.Column('metadata_fingerprint', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migration_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repository_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('source_item_id', sa.String(length=200), nullable=False),
    sa.Column('parent_source_id', sa.String(length=200), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('trashed', sa.Boolean(), nullable=False),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('logical_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'source_item_id', name='uq_repo_item_snapshot_source')
    )
    op.create_index(op.f('ix_repository_items_logical_path'), 'repository_items', ['logical_path'], unique=False)
    op.create_index(op.f('ix_repository_items_parent_source_id'), 'repository_items', ['parent_source_id'], unique=False)
    op.create_index(op.f('ix_repository_items_snapshot_id'), 'repository_items', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_repository_items_source_item_id'), 'repository_items', ['source_item_id'], unique=False)
    op.create_table('batch_selectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('include', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['migration_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_selectors_batch_id'), 'batch_selectors', ['batch_id'], unique=False)
    op.create_table('migration_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('source_item_id', sa.String(length=200), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_mime_type', sa.String(length=200), nullable=True),
    sa.Column('source_size', sa.Integer(), nullable=True),
    sa.Column('source_version', sa.String(length=128), nullable=True),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('planned_destination_path', sa.Text(), nullable=True),
    sa.Column('planned_destination_name', sa.Text(), nullable=True),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('rename_method', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('downloaded_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_bytes', sa.Integer(), nullable=False),
    sa.Column('local_temp_path', sa.Text(), nullable=True),
    sa.Column('local_sha256', sa.String(length=64), nullable=True),
    sa.Column('remote_size', sa.Integer(), nullable=True),
    sa.Column('remote_hash', sa.String(length=128), nullable=True),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=60), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['migration_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_migration_item_idempotency_key')
    )
    op.create_index(op.f('ix_migration_items_batch_id'), 'migration_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_migration_items_idempotency_key'), 'migration_items', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_migration_items_state'), 'migration_items', ['state'], unique=False)
    op.create_table('migration_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['migration_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_plans_batch_id'), 'migration_plans', ['batch_id'], unique=False)
    op.create_table('name_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('migration_item_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('suggested_name', sa.String(length=255), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['migration_item_id'], ['migration_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_name_decisions_migration_item_id'), 'name_decisions', ['migration_item_id'], unique=False)
    op.create_table('transfer_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('migration_item_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('bytes_transferred', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['migration_item_id'], ['migration_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_checkpoints_migration_item_id'), 'transfer_checkpoints', ['migration_item_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('migration_item_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['migration_item_id'], ['migration_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_migration_item_id'), 'validation_results', ['migration_item_id'], unique=False)
    op.create_table('worker_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('migration_item_id', sa.String(length=36), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['migration_item_id'], ['migration_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('migration_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_leases')
    op.drop_index(op.f('ix_validation_results_migration_item_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_transfer_checkpoints_migration_item_id'), table_name='transfer_checkpoints')
    op.drop_table('transfer_checkpoints')
    op.drop_index(op.f('ix_name_decisions_migration_item_id'), table_name='name_decisions')
    op.drop_table('name_decisions')
    op.drop_index(op.f('ix_migration_plans_batch_id'), table_name='migration_plans')
    op.drop_table('migration_plans')
    op.drop_index(op.f('ix_migration_items_state'), table_name='migration_items')
    op.drop_index(op.f('ix_migration_items_idempotency_key'), table_name='migration_items')
    op.drop_index(op.f('ix_migration_items_batch_id'), table_name='migration_items')
    op.drop_table('migration_items')
    op.drop_index(op.f('ix_batch_selectors_batch_id'), table_name='batch_selectors')
    op.drop_table('batch_selectors')
    op.drop_index(op.f('ix_repository_items_source_item_id'), table_name='repository_items')
    op.drop_index(op.f('ix_repository_items_snapshot_id'), table_name='repository_items')
    op.drop_index(op.f('ix_repository_items_parent_source_id'), table_name='repository_items')
    op.drop_index(op.f('ix_repository_items_logical_path'), table_name='repository_items')
    op.drop_table('repository_items')
    op.drop_table('migration_batches')
    op.drop_table('repository_snapshots')
    op.drop_table('repository_connections')
    op.drop_index(op.f('ix_journal_events_timestamp'), table_name='journal_events')
    op.drop_index(op.f('ix_journal_events_migration_item_id'), table_name='journal_events')
    op.drop_index(op.f('ix_journal_events_correlation_id'), table_name='journal_events')
    op.drop_index(op.f('ix_journal_events_batch_id'), table_name='journal_events')
    op.drop_table('journal_events')
    # ### end Alembic commands ###
